- package.json
- src/lib/github.js
- src/lib/npm.js
> chore: update inquirer

- .travis.yml
- src/lib/travis.js
iojs v3.0.0 - https://github.com/nodejs/io.js/blob/master/CHANGELOG.md
> test(travis): added iojs v3 to .travis.yml and .travis.yml generator

- .travis.yml
- package.json
- src/index.js
- src/lib/github.js
- src/lib/npm.js
- src/lib/password-storage.js
Store npm and github passwords in the keychain. Can be disabled via
`--no-keychain` flag.
Closes #13
> feat: Remember passwords

- src/lib/travis.js
follow up for https://github.com/semantic-release/cli/pull/36
> Node 4 & ignore builds from git tags

- .cz.json
- README.md
- package.json
Clarifying the README.md, per the thread in #25.
> Revamping README.md

- README.md
- src/index.js
> feat: add init option as an alternative to setup

- README.md
- src/index.js
- src/lib/github.js
- src/lib/npm.js
See https://github.com/semantic-release/semantic-release/issues/434
> feat: Add gh- and npm-username opts

- src/index.js
See https://github.com/semantic-release/cli/pull/130#issuecomment-330231429.
> style: Remove comma

- README.md
- package.json
- src/lib/github.js
> feat: get GitHub username from global .gitconfig

- package.json
> update semantic-release to version 8.0.0

- package.json
> chore(package): update keytar to version 4.0.4

- package.json
- src/index.js
- src/lib/github.js
- src/lib/npm.js
- src/lib/password-storage.js
closes #98, closes #106, closes #108, closes #109, closes #110, closes #113, closes #134, closes #139
> WIP dependency updates

- src/lib/travis.js
> travis updates

- src/lib/npm.js
> remove logging npm password

- src/lib/github.js
- src/lib/npm.js
> display more helpful error message on broken keychain

- bin/semantic-release.js
Workaround for babel/babel#5487
Fix semantic-release/semantic-release#523
> Compile only local sources

- bin/semantic-release.js
- package.json
- src/index.js
- src/lib/ci.js
- src/lib/github.js
- src/lib/npm.js
- src/lib/password-storage.js
- src/lib/repository.js
- src/lib/travis.js
That's quite a lot of fixes...A lot of of `var` used outside of binding context, some unused function parameters, and `process.exit`.
There are some that require more work for which I disabled the rule ([here](https://github.com/semantic-release/cli/pull/154/files#diff-0d0a3500cd00a430ba034310678baa9aL49) for example).
Can you review @gr2m ? Thanks
> Lint with XO

- README.md
- src/lib/travis.js
Related to semantic-release/semantic-release#578.
Require semantic-release/travis-deploy-once#38 to be released.
> Add `travis-deploy-once` CLI

- src/lib/circle.js
- src/lib/npm.js
- src/lib/travis.js
Fixes 4 open issues regarding npm logic. Please see individual commits for details.
Fixes #60, fixes #107, fixes #18, fixes #79.
> fix(npm): various fixes to the cli npm logic

- src/lib/travis.js
Per [comment](https://github.com/semantic-release/semantic-release/pull/578#issuecomment-354587834)
> Setup travis-deploy-once locally

- src/lib/npm.js
> fix(npm): proper error handling in case of succesful authentication without 2fa

- package.json
> Update prettier to the latest version 🚀

- .travis.yml
- README.md
- package.json
> test: disable codecov until we write tests

- src/lib/travis.js
> fix: bind promisified function to travis client

- src/lib/ci.js
- src/lib/travis.js
> fix(travis): fix travis-deploy-once usage with Travis Pro/Enterprise

- src/lib/travis.js
> fix(travis): update error message when repo not found on Travis

- src/lib/travis.js
Ref semantic-release/travis-deploy-once#105
This remove the added `devDependency` to `travis-deploy-once` in `package.json` and the modifications of `.travis.yml`.
If Travis is chosen as a CI we just log a link to https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/travis.md instead of generating/modifying the user `.travis.yml`.
I guess this can be improved in the future by either generating a basic `.travis.yml` if none is present or maybe attempt to modify the existing one by adding a `release` `stage` to `jobs.include`.
I intend to rewrite the CLI from scratch as some point in the future, where I will handle that case. In the meantime we will accept contribution to this project adding such feature.
> feat: remove `travis-deploy-once` from output config

- src/lib/github.js
In preparation for github-npm-registry plugin
> feat: add read:packages / write:packages to scopes

- README.md
- src/lib/repository.js
- src/lib/travis.js
> style: (pencil) hint repo url in the error message

- package.json
- src/lib/ci.js
- src/lib/github-actions.js
Hey guys, I've added the Github Actions Integration.
Please let me know what would you like me to change in terms of code. There is obviously a duplication of ask2FA function - I would like to extract that one to some helper but you don't have a pattern for that, so didn't want to introduce my own.
Thanks for all your great work!
> feat: Add GitHub Actions integration

- src/index.js
- src/lib/npm.js
> feat: throw error when "name" key is missing in package.json

- bin/semantic-release.js
- package-lock.json
- package.json
> fix(babel): removed inline transpilation that appears to be unnecessary
